plugins:
  flexiant:
    executor: central_deployment_agent
    source: https://github.com/b-77/cloudify-plugin-template/archive/3.2-build.zip

node_types:
  cloudify.flexiant.nodes.Server:
    derived_from: cloudify.nodes.Compute
    properties:
      auth: {}
      image_uuid: {}
      key_uuid: {}
      net_uuid: {}
      net_type:
        default: 'IP'
      cpu_count:
        default: 2
      ram_amount:
        default: 2048
      server_type:
        default: '2 GB / 2 CPU'
      install_agent:
        default: true
      cloudify_agent:
        default: {}
      # TODO: remove once types get fixed
      os:
        default:
          type: 'linux'
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: flexiant.wrapper.server.create
        start:
          implementation: flexiant.wrapper.server.start
        stop:
          implementation: flexiant.wrapper.server.stop
        delete:
          implementation: flexiant.wrapper.server.delete
      cloudify.interfaces.validation:
        creation:
          implementation: flexiant.wrapper.server.creation_validation
