plugins:
  flexiant:
    executor: central_deployment_agent
    source: https://github.com/b-77/cloudify-plugin-template/archive/3.2-build.zip

node_types:
  cloudify.flexiant.nodes.Server:
    derived_from: cloudify.nodes.Compute
    properties:
      image_uuid: {}
      net_type:
        default: 'IP'
      cpu_count:
        default: 2
      ram_amount:
        default: 2048
      server_type:
        default: '2 GB / 2 CPU'
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: fcoclient.server.create
        start:
          implementation: fcoclient.server.start
        stop:
          implementation: fcoclient.server.stop
        delete:
          implementation: fcoclient.server.delete
      cloudify.interfaces.validation:
        creation:
          implementation: fcoclient.server.creation_validation
